---
# ----------------------------------------
# проектный файл для проекта "nbd" 
# ----------------------------------------
project:
  start: main/usr.json  # файл - с которого можно начать чтение, в нем могут быть ссылки на другие файлы

  name: nbd       # уникальное имя проекта 

  files:          # список файлов проекта - массив строк
  - main:         # каждый элемент массива - это подпапка в каталоге проекта на сервере. Например папка /main
    - usr.json
    - forms.json
  - scripts:      # подкаталог со скриптами /scripts
    - nbd_logicJs.js
    - nbd_nodes.js
    - nbd_android_api.js
    - nbd_rzhd.js
    - nbd_api.js
    - nbd_helpers.js
    - autosync.js
    - setupkeonvagon.js
    - cleanup_logs_st.js
    - applications_logic.js
    - nbd_files_processing.js
    - nbd_pasportgenerator_logic.js
    - nbd_batch.js
    - autosendmail.js
    - autosendrequestpost.js
    - autosendrequestget.js
    - log_helper.js
    - autogeneratebarcodes.js
    - dictionaries_logic.js
    - autocountingcompletedoperations.js
  - images:       # подкаталог с изображениями /images
    - banner.png
    - basic.png
    - logo.png
    - logo1.png
    - logo2.png
  - reports:
    - reportkenumbers.mrt
    - reportdatabasefilling.mrt
    - reportdetailsinstalledonfreightwagons.mrt
    - reportnumbersgeneration.mrt
    - reportonyearsofrepairskeyelements.mrt
    - reportstatusonkeyelement.mrt
    - reportuseractivity.mrt
    - reportbarcodes.mrt
    - reportrfidrequestbarcodes.mrt
    - reportacceptapplicationform.mrt
    - reportdeclineapplicationform.mrt
    - reportregisternumbersapplication.mrt
    - reportacceptregisternumbersapplication.mrt
    - reportdeclineregisternumbersapplication.mrt
    - reportnoticeforregistrationkeyelement.mrt
    - reportacceptregisterelementapplication.mrt
    - reportdeclineregisterelementapplication.mrt
    - reportnoticeforregistrationvagon.mrt
    - reportacceptregisterelementsonvagonapplications.mrt
    - reportdeclineregisterelementsonvagonapplication.mrt
    - reportnoticeforregistrationassemblyunit.mrt
    - reportnoticeforregistrationmultiplekeyelement.mrt
    - reportnoticeforregistrationmultipleassemblyunit.mrt
    - reportnoticeforregistrationkeyelementwithhash.mrt
    - reportnoticeforregistrationmultiplekeyelementwithhash.mrt
    - reportnoticeforregistrationassemblyunitwithhash.mrt
    - reportnoticeforregistrationvagonwithhash.mrt
    - reportnoticeforregistrationmultipleassemblyunitwithhash.mrt
  - plugins:
    - replacekeyelement-plugin/2.ffe6b999.chunk.css
    - replacekeyelement-plugin/2.777c7519.chunk.js
    - replacekeyelement-plugin/main.712dbe2b.chunk.js
    - replacekeyelement-plugin/main.e34a4f0a.chunk.css
    - replacekeyelement-plugin/runtime-main.1f6e9381.js
    - masscreatekeyelement-plugin/2.ff25740b.chunk.js
    - masscreatekeyelement-plugin/main.5a5f9fe0.chunk.css
    - masscreatekeyelement-plugin/2.bbfed612.chunk.css
    - masscreatekeyelement-plugin/main.4b04e436.chunk.js
    - masscreatekeyelement-plugin/runtime-main.1f6e9381.js
    - repairregistration/2.6f1275a5.chunk.js
    - repairregistration/main.c4c05350.chunk.css
    - repairregistration/2.a2b291d0.chunk.css
    - repairregistration/main.59e60663.chunk.js
    - repairregistration/runtime-main.1f6e9381.js