---
# ----------------------------------------
# проектный файл для проекта "ВИС Лицензирование" 
# ----------------------------------------
project:
  start: main/usr.json  # файл - с которого можно начать чтение, в нем могут быть ссылки на другие файлы

  name: RDEV_license  # уникальное имя проекта 

  files:          # список файлов проекта - массив строк
  - main:         # каждый элемент массива - это подпапка в каталоге проекта на сервере. Например папка /main
    - usr.json
    - forms.json
  - scripts:      # подкаталог со скриптами /scripts
    - shadow_tasks.js
    - helpers.js
    - buttons_methods.js
  - images:       # подкаталог с изображениями /images
    - banner.png
    - basic.png
    - logo.png
    - logo1.png
    - logo2.png
  - reports:
    - reportlicenseregister.mrt
    - receivedapplicationreport.mrt
    - receivedlomapplicationreport.mrt
    - receivedalcoapplicationreport.mrt
    - receivedtaxiapplicationreport.mrt
    - receivedmkdapplicationreport.mrt
    - licenseregistergischargereport.mrt
    - noticerefusalpermissionissuereport.mrt
    - orderrefusalpermissionissuereport.mrt
    - orderreportdocument.mrt
    - checkreportdocument.mrt
    - notificationoftheneedforelimination.mrt
    - applicationforlicenseduplicateforip.mrt
    - applicationforlicenseduplicateforul.mrt
    - applicationforlicenserenewalforip.mrt
    - applicationforlicenserenewalforul.mrt
    - statementongrantinglicensetoip.mrt
    - statementongrantinglicensetoul.mrt
    - licensealcohol.mrt
